---
name: Load Parameters
description: Load parameters for the workflow

inputs:
  build_options_file:
    description: The file containing build options
    required: true
    type: string
    default: 'ci/build_options.txt'

outputs:
  build_args:
    description: The build arguments
    value: ${{ steps.parse_args.outputs.build_args }}

runs:
  using: 'composite'
  steps:
    - name: Parse the build arguments
      id: parse_args
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = `${{ github.workspace }}/${{ inputs.build_options_file }}`;

          let options = '';

          try {
            if (fs.existsSync(path)) {
              options = fs.readFileSync(path).toString().trim().split('\n').join(' ');
            } else {
              console.log(`⚠️ File not found: ${path}. Proceeding with empty options.`);
            }
          } catch (err) {
            console.log(`❌ Error reading file: ${err}. Using empty options.`);
          }

          console.log(`Parsed options: "${options}"`);
          core.setOutput('build_args', options);
